name: Acromere Seenc CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

env:
  ACM_GPG_PASSWORD: ${{ secrets.ACM_GPG_PASSWORD }}
  ACM_KEYSTORE_PASSWORD: ${{ secrets.ACM_KEYSTORE_PASSWORD }}
  ACM_MAVEN_REPO_USERNAME: ${{ secrets.ACM_MAVEN_REPO_USERNAME }}
  ACM_MAVEN_REPO_PASSWORD: ${{ secrets.ACM_MAVEN_REPO_PASSWORD }}
  ACM_XENON_REPO_USERNAME: ${{ secrets.ACM_XENON_REPO_USERNAME }}
  ACM_XENON_REPO_PASSWORD: ${{ secrets.ACM_XENON_REPO_PASSWORD }}

  GITHUB_REF: ${{ github.ref }}
  JAVA_VERSION: "21"
  MAVEN_PARMS: "-B -U -V --settings .github/settings.xml --file pom.xml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch sources
      uses: actions/checkout@v6

    - name: Fetch CI/CD resources
      uses: actions/checkout@v6
      with:
        repository: acromere/canoe
        path: .github

    - name: Configuration
      shell: bash
      run: |
        source .github/config.sh

    - name: Set up Java
      uses: actions/setup-java@v5
      with:
        distribution: ${{env.JAVA_DISTRO}}
        java-version: ${{env.JAVA_VERSION}}

    - name: Compile
      run: |
        mvn ${{env.MAVEN_PARMS}} compile

    - name: Test
      run: |
        mvn ${{env.MAVEN_PARMS}} test

    - name: Deploy
      run: |
        mvn ${{env.MAVEN_PARMS}} deploy -Dmaven.test.skip=true

    - name: Publish
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/stable' || github.base_ref == 'refs/heads/main' || github.base_ref == 'refs/heads/stable'
      run: .github/deploy.sh
