name: Acromere Seenc CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

env:
  ACM_PRODUCT: "seenc"
  # The default release, should be overridden in config.sh
  ACM_RELEASE: "latest"
  # The default platform, should be overridden in the platform binaries jobs below
  ACM_PLATFORM: "linux"

  ACM_GPG_PASSWORD: ${{ secrets.ACM_GPG_PASSWORD }}
  ACM_KEYSTORE_PASSWORD: ${{ secrets.ACM_KEYSTORE_PASSWORD }}
  ACM_MAVEN_REPO_USERNAME: ${{ secrets.ACM_MAVEN_REPO_USERNAME }}
  ACM_MAVEN_REPO_PASSWORD: ${{ secrets.ACM_MAVEN_REPO_PASSWORD }}
  ACM_XENON_REPO_USERNAME: ${{ secrets.ACM_XENON_REPO_USERNAME }}
  ACM_XENON_REPO_PASSWORD: ${{ secrets.ACM_XENON_REPO_PASSWORD }}

  DISPLAY: ":99"
  GITHUB_REF: ${{ github.ref }}
  JAVA_VERSION: "21"
  MAVEN_PARMS: "-B -U -V --settings .github/settings.xml --file pom.xml"
  XVFB_PARMS: "-screen 0 1920x1080x24 -nolisten unix"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch sources
      uses: actions/checkout@v6

    - name: Fetch CI/CD resources
      uses: actions/checkout@v6
      with:
        repository: acromere/canoe
        path: .github

    - name: Configuration
      shell: bash
      run: |
        source .github/config.sh

    - name: Set up Java
      uses: actions/setup-java@v5
      with:
        distribution: ${{env.JAVA_DISTRO}}
        java-version: ${{env.JAVA_VERSION}}

    - name: Compile
      run: |
        mvn ${{env.MAVEN_PARMS}} compile

    - name: Test
      run: |
        mvn ${{env.MAVEN_PARMS}} test

    - name: Deploy
      run: |
        mvn ${{env.MAVEN_PARMS}} deploy -Dmaven.test.skip=true

#    - name: Deploy Product Icon
#      run: |
#        ssh -t ${{env.ACM_XENON_REPO_USERNAME}}@acromere.com "mkdir -p ${{env.PRODUCT_DEPLOY_PATH}};"
#        if [ $? -ne 0 ]; then exit 1; fi
#        scp -B target/main/images/${ACM_PRODUCT}.png ${{env.ACM_XENON_REPO_USERNAME}}@acromere.com:${PRODUCT_DEPLOY_PATH}/product.png 2>&1

    - name: Deploy Product Pack
      run: |
        ssh -t ${{env.ACM_XENON_REPO_USERNAME}}@acromere.com "mkdir -p ${{env.PRODUCT_DEPLOY_PATH}};"
        if [ $? -ne 0 ]; then exit 1; fi
        scp -B target/*product.jar ${{env.ACM_XENON_REPO_USERNAME}}@acromere.com:${{env.PRODUCT_DEPLOY_PATH}} 2>&1

    - name: Deploy Product Card
      run: |
        ssh -t ${{env.ACM_XENON_REPO_USERNAME}}@acromere.com "mkdir -p ${{env.PRODUCT_DEPLOY_PATH}};"
        if [ $? -ne 0 ]; then exit 1; fi
        scp -B target/main/java/META-INF/*.card ${{env.ACM_XENON_REPO_USERNAME}}@acromere.com:${{env.PRODUCT_DEPLOY_PATH}} 2>&1
